### PR TITLE
bug:Unflexible TUFilm Parser

### LINKED ISSUE #263: Display of Movie's Location
Is it possible to pass the location of the movie entry?

### LINKED ISSUE #267: Some tu-film movies don't have an imdb link
See https://www.tu-film.de/programm/view/1233

=> this breaks the movies cronjob

### PR DESCRIPTION
**Pull request by CommanderStorm**
this PR makes the tufilm parser more flexible

Resolves #267
Resolves #263

TODO:
- [x] Redo the main logic of the omdb handling
- [x] look if the api or db schema needs modifications

### CODE REVIEW

File: server/backend/cron/movies.go [hunk 1]
```diff
@@ -1,59 +1,37 @@
...
-
 const (
 	MovieImageDirectory = "movie/"
 )
 
 func (c *CronService) movieCron() error {
 	log.Trace("parsing upcoming feed")
-	channels, err := parseUpcomingFeed()
+	var allMovieLinks []string
+	if err := c.db.Model(&model.Kino{}).Distinct().Pluck("Link", &allMovieLinks).Error; err != nil {
```
Comment (tobiasjungmann) [inline server/backend/cron/movies.go:23]: The table "kino" doesn't have the column "Link" in my instance which leads to an error.

**Comment by tobiasjungmann** [comment]
Can you add a description e.g. the readme on how to obtain the ombd api key which is used as an environment variable. Otherwise chances are high that this feature will be overlooked in a lot of local test setups

Do you know how long the Information used in tufilm_test.go is available? Are thy deleted right after the viewing? In this case we should add an annotation to simplify the test setup for new movies, depending on the current program.

File: server/backend/cron/movies.go (hunk 1 above)
Comment (CommanderStorm) [reply server/backend/cron/movies.go:23]: image

Cannot reproduce this exact issue.
The column exists both on fresh re-running main and this branch.
I have fixed a bug though which lead to fresh rerunning failing => this might be a culprit.

**Comment by CommanderStorm** [comment]
> Do you know how long the Information used in tufilm_test.go is available? Are thy deleted right after the viewing?

Unclear what you mean.
I picked 3 different movies each with different characteristics (Surprise film [does have most fields not filled out], Babylon [does have the trailer field filled out] and Oppenheimer [normal film])

> In this case we should add an annotation to simplify the test setup for new movies, depending on the current program

I don't expect we will need more films. With the current setup, we get full test coverage of all the cases that I could get from past trends.

**Comment by CommanderStorm** [comment]
Merging as I wan't to display the current films
